# Это файл запуска процесса на stage
services:

  example:
    build: .
    volumes:
      - ./src/.:/app/.
      - ./doc/.:/doc
    command: bash -c "python /doc/example1.py"

  tests:
    build: .
    volumes:
      - ./src/.:/app/.
      - ./tests/.:/tests
    command: bash -c "python -m pytest /tests/* --log-cli-level=INFO"
