name: new-release

on:
  workflow_dispatch:

jobs:

  new-release:

    name: start new release
    runs-on: ubuntu-latest

    steps:
    - name: start new release
      run: echo "start new release"
