---
name: PyTest

on:

  workflow_run:
    workflows: ["new-release"]
    branches: [ master ]
    types: [completed]
  # push:
  #   branches:
  #     - main
  #     - master
  #   paths-ignore:
  #   - '.github/workflows/*'

jobs:
  tests:
      name: pytest tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: "./src"
          MYGITHUB_OWNER: "strukovsv"
          MYGITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
          MYGITHUB_REPO: "PAQLang" 
          MYGITHUB_BRANCH: "master"
        run: |
          pip install pytest
          cd src
          python -m pytest ../tests/main/test* --log-cli-level=INFO
          python -m pytest ../tests/github/test* --log-cli-level=INFO
